workflows:
  android:
    name: Build Android APK with Buildozer
    max_build_duration: 60
    environment:
      vars:
        BUILD_NUMBER: 1
    scripts:
      - name: Install dependencies
        script: |
          sudo apt-get update
          sudo apt-get install -y libzbar-dev python3 python3-pip
          pip install --upgrade buildozer cython
      - name: Build APK
        script: |
          buildozer -v android debug
    artifacts:
      - build/*.apk
