workflows:
  android:
    name: Build Android APK with Buildozer
    max_build_duration: 60
    environment:
      vars:
        BUILD_NUMBER: 1
    scripts:
      - name: Install dependencies
        script: |
          brew install zbar
          brew install --cask android-sdk
          export ANDROID_HOME=$HOME/Library/Android/sdk
          export PATH=$ANDROID_HOME/tools:$ANDROID_HOME/tools/bin:$ANDROID_HOME/platform-tools:$PATH
          yes | sdkmanager --licenses
          sdkmanager "build-tools;35.0.0" "platforms;android-31"
      - name: Build APK
        script: |
          buildozer -v android debug
    artifacts:
      - build/*.apk
